### PR TITLE
Fixed several bugs #87, #90, #93

### PR DESCRIPTION
**Pull request by jeffdc**

### CODE REVIEW

**Comment by Megachile** [comment]
Dashes work.

The direct link to Map Species & Sources works but the page itself is now broken for me, at least to edit. If I select an existing source, the description doesn't load at first, and when I click the description field, it flashes the text in for a microsecond, then everything except the species disappears. Presumably related to #90 but makes it so I can't test your fix of that one otherwise. 

The large image selection modals aren't working at all. The images load on the species page and I can scroll through them but if I click to enlarge it just says "photo of [gall]" but there's no image. (incidentally I'm not sure we should default to the word "photo" here since some of these are going to be drawings?)

**Comment by Megachile** [comment]
Confirmed that adding a new source-species mapping works fine, it's just trying to edit an existing one that's not working.

**Comment by jeffdc** [comment]
Hmmm ok. I did some local testing but I guess it was not sufficient. Will check it out in the AM.

**Comment by jeffdc** [comment]
Fixed the speciessource mapping page issue and the image issue. For now just loading the originals when you click on the images. My "clever" workaround to try and load XL images for new ones and original for old one turns out not to have been very clever as it did not work. Oddly it worked locally for me. 😕

**Comment by Megachile** [comment]
Both of those fixes work for me too, I can edit now. The original images look great :o 

Testing your fix for #90, it's still failing to clear the link field but now it's also failing to clear the description field.

**Comment by jeffdc** [comment]
Ugh. I spent most of time trying to get the logic all correct for all of the states that that speciessource mapping page can be in and apparently I messed it up worse. Looking now.

**Pull request merged**
